// Code generated by "stringer -type Kind"; DO NOT EDIT.

package cc // import "modernc.org/cc"

import "fmt"

const _Kind_name = "UndefinedVoidPtrUintPtrCharSCharUCharShortUShortIntUIntLongULongLongLongULongLongFloatDoubleLongDoubleBoolFloatComplexDoubleComplexLongDoubleComplexStructUnionEnumTypedefNameFunctionArraytypeofkindMax"

var _Kind_index = [...]uint8{0, 9, 13, 16, 23, 27, 32, 37, 42, 48, 51, 55, 59, 64, 72, 81, 86, 92, 102, 106, 118, 131, 148, 154, 159, 163, 174, 182, 187, 193, 200}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
