BEGIN;

ALTER TABLE IF EXISTS public.characters
    ALTER COLUMN daily_time TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.characters
    ALTER COLUMN guild_post_checked TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.characters
    ALTER COLUMN boost_time TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.characters
    ALTER COLUMN cafe_reset TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.distribution
    ALTER COLUMN deadline TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.events
    ALTER COLUMN start_time TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.feature_weapon
    ALTER COLUMN start_time TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.guild_alliances
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.guild_applications
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.guild_characters
    ALTER COLUMN joined_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.guild_posts
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.characters
    ALTER COLUMN daily_time TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.guilds
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.mail
    ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.stamps
    ALTER COLUMN hl_next TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.stamps
    ALTER COLUMN ex_next TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.titles
    ALTER COLUMN unlocked_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.titles
    ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.users
    ALTER COLUMN last_login TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.users
    ALTER COLUMN return_expires TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS public.guild_meals
    DROP COLUMN expires;

ALTER TABLE IF EXISTS public.guild_meals
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;

END;