// Code generated by "stringer -output stringer.go -type=cond,Linkage,StorageDuration enum.go"; DO NOT EDIT.

package cc

import "strconv"

const _cond_name = "condZerocondIfOffcondIfOncondIfSkipmaxCond"

var _cond_index = [...]uint8{0, 8, 17, 25, 35, 42}

func (i cond) String() string {
	if i < 0 || i >= cond(len(_cond_index)-1) {
		return "cond(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _cond_name[_cond_index[i]:_cond_index[i+1]]
}

const _Linkage_name = "LinkageNoneLinkageExternalLinkageInternal"

var _Linkage_index = [...]uint8{0, 11, 26, 41}

func (i Linkage) String() string {
	if i < 0 || i >= Linkage(len(_Linkage_index)-1) {
		return "Linkage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Linkage_name[_Linkage_index[i]:_Linkage_index[i+1]]
}

const _StorageDuration_name = "StorageDurationAutomaticStorageDurationStatic"

var _StorageDuration_index = [...]uint8{0, 24, 45}

func (i StorageDuration) String() string {
	if i < 0 || i >= StorageDuration(len(_StorageDuration_index)-1) {
		return "StorageDuration(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageDuration_name[_StorageDuration_index[i]:_StorageDuration_index[i+1]]
}
