BEGIN;

CREATE TABLE IF NOT EXISTS public.account_ban
(
    user_id integer NOT NULL,
    title text COLLATE pg_catalog."default",
    reason text COLLATE pg_catalog."default",
    date text COLLATE pg_catalog."default",
    pass_origin text COLLATE pg_catalog."default",
    pass_block text COLLATE pg_catalog."default",
    CONSTRAINT ban_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.account_history
(
    report_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer,
    title text COLLATE pg_catalog."default",
    reason text COLLATE pg_catalog."default",
    date date,
    CONSTRAINT account_history_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS public.account_moderation
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    CONSTRAINT account_moderation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.account_sub
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    discord_id text COLLATE pg_catalog."default",
    erupe_account text COLLATE pg_catalog."default",
    erupe_password text COLLATE pg_catalog."default",
    date_inscription date,
    country text COLLATE pg_catalog."default",
    presentation text COLLATE pg_catalog."default",
    CONSTRAINT account_auth_pkey PRIMARY KEY (id)
);

END;